// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCzyV4Ck5bkgTm1ECJ0V9Lwi6TEFO_c3Ag',
//     appId: '1:408750961465:android:cd2b5520d67e80da586ee8',
//     messagingSenderId: '408750961465',
//     projectId: 'the-logistics',
//     storageBucket: 'the-logistics.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCkEzb5SbaKjYQ9IER8N1nYsSh7qju39Ak',
//     appId: '1:408750961465:ios:a42bef5171d48523586ee8',
//     messagingSenderId: '408750961465',
//     projectId: 'the-logistics',
//     storageBucket: 'the-logistics.firebasestorage.app',
//     iosBundleId: 'com.example.retilda',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCkEzb5SbaKjYQ9IER8N1nYsSh7qju39Ak',
//     appId: '1:408750961465:ios:86d47f673ec29b94586ee8',
//     messagingSenderId: '408750961465',
//     projectId: 'the-logistics',
//     storageBucket: 'the-logistics.firebasestorage.app',
//     iosBundleId: 'com.example.retilda.RunnerTests',
//   );
// }
